export const gridMapping: Record<string, string> = {
  // Grid
  grid: "display: grid;",
  "grid-cols-1": "grid-template-columns: repeat(1, minmax(0, 1fr));",
  "grid-cols-2": "grid-template-columns: repeat(2, minmax(0, 1fr));",
  "grid-cols-3": "grid-template-columns: repeat(3, minmax(0, 1fr));",
  "grid-rows-1": "grid-template-rows: repeat(1, minmax(0, 1fr));",
  "grid-rows-2": "grid-template-rows: repeat(2, minmax(0, 1fr));",
  "grid-rows-3": "grid-template-rows: repeat(3, minmax(0, 1fr));",
  "justify-items-center": "justify-items: center;",
  "content-center": "align-content: center;",
  "gap-4": "gap: 1rem;",
  "gap-6": "gap: 1.5rem;",
  "gap-8": "gap: 2rem;",
  "gap-12": "gap: 3rem;",
  "gap-16": "gap: 4rem;",
  "gap-20": "gap: 5rem;",
  "gap-24": "gap: 6rem;",
  "gap-32": "gap: 8rem;",
  "gap-40": "gap: 10rem;",
  "gap-48": "gap: 12rem;",
  "gap-56": "gap: 14rem;",
  "gap-64": "gap: 16rem;",
  "gap-72": "gap: 18rem;",
  "gap-80": "gap: 20rem;",
  "gap-96": "gap: 24rem;",
  "gap-px": "gap: 1px;",
  "col-span-1": "grid-column: span 1 / span 1;",
  "col-span-2": "grid-column: span 2 / span 2;",
  "col-span-3": "grid-column: span 3 / span 3;",
  "col-span-4": "grid-column: span 4 / span 4;",
  "col-span-5": "grid-column: span 5 / span 5;",
  "col-span-6": "grid-column: span 6 / span 6;",
  "col-span-7": "grid-column: span 7 / span 7;",
  "col-span-8": "grid-column: span 8 / span 8;",
  "col-span-9": "grid-column: span 9 / span 9;",
  "col-span-10": "grid-column: span 10 / span 10;",
  "col-span-11": "grid-column: span 11 / span 11;",
  "col-span-12": "grid-column: span 12 / span 12;",
  "col-start-1": "grid-column-start: 1;",
  "col-start-2": "grid-column-start: 2;",
  "col-start-3": "grid-column-start: 3;",
  "col-start-4": "grid-column-start: 4;",
  "col-start-5": "grid-column-start: 5;",
  "col-start-6": "grid-column-start: 6;",
  "col-start-7": "grid-column-start: 7;",
  "col-start-8": "grid-column-start: 8;",
  "col-start-9": "grid-column-start: 9;",
  "col-start-10": "grid-column-start: 10;",
  "col-start-11": "grid-column-start: 11;",
  "col-start-12": "grid-column-start: 12;",
  "col-end-1": "grid-column-end: 1;",
  "col-end-2": "grid-column-end: 2;",
  "col-end-3": "grid-column-end: 3;",
  "col-end-4": "grid-column-end: 4;",
  "col-end-5": "grid-column-end: 5;",
  "col-end-6": "grid-column-end: 6;",
  "col-end-7": "grid-column-end: 7;",
  "col-end-8": "grid-column-end: 8;",
  "col-end-9": "grid-column-end: 9;",
  "col-end-10": "grid-column-end: 10;",
  "col-end-11": "grid-column-end: 11;",
  "col-end-12": "grid-column-end: 12;",
  "row-span-1": "grid-row: span 1 / span 1;",
  "row-span-2": "grid-row: span 2 / span 2;",
  "row-span-3": "grid-row: span 3 / span 3;",
  "row-span-4": "grid-row: span 4 / span 4;",
  "row-span-5": "grid-row: span 5 / span 5;",
  "row-span-6": "grid-row: span 6 / span 6;",
  "row-span-7": "grid-row: span 7 / span 7;",
  "row-span-8": "grid-row: span 8 / span 8;",
  "row-span-9": "grid-row: span 9 / span 9;",
  "row-span-10": "grid-row: span 10 / span 10;",
  "row-span-11": "grid-row: span 11 / span 11;",
  "row-span-12": "grid-row: span 12 / span 12;",
  "row-start-1": "grid-row-start: 1;",
  "row-start-2": "grid-row-start: 2;",
  "row-start-3": "grid-row-start: 3;",
  "row-start-4": "grid-row-start: 4;",
  "row-start-5": "grid-row-start: 5;",
  "row-start-6": "grid-row-start: 6;",
  "row-start-7": "grid-row-start: 7;",
  "row-start-8": "grid-row-start: 8;",
  "row-start-9": "grid-row-start: 9;",
  "row-start-10": "grid-row-start: 10;",
  "row-start-11": "grid-row-start: 11;",
  "row-start-12": "grid-row-start: 12;",
  "row-end-1": "grid-row-end: 1;",
  "row-end-2": "grid-row-end: 2;",
  "row-end-3": "grid-row-end: 3;",
  "row-end-4": "grid-row-end: 4;",
  "row-end-5": "grid-row-end: 5;",
  "row-end-6": "grid-row-end: 6;",
  "row-end-7": "grid-row-end: 7;",
  "row-end-8": "grid-row-end: 8;",
  "row-end-9": "grid-row-end: 9;",
  "row-end-10": "grid-row-end: 10;",
  "row-end-11": "grid-row-end: 11;",
  "row-end-12": "grid-row-end: 12;",
  "auto-cols-auto": "grid-auto-columns: auto;",
  "auto-cols-min": "grid-auto-columns: min-content;",
  "auto-cols-max": "grid-auto-columns: max-content;",
  "auto-rows-auto": "grid-auto-rows: auto;",
  "auto-rows-min": "grid-auto-rows: min-content;",
  "auto-rows-max": "grid-auto-rows: max-content;",
  "auto-flow-row": "grid-auto-flow: row;",
  "auto-flow-col": "grid-auto-flow: column;",
  "auto-flow-row-dense": "grid-auto-flow: row dense;",
  "auto-flow-col-dense": "grid-auto-flow: column dense;",
  "gap-0": "gap: 0;",
  "gap-0.5": "gap: 0.125rem;",
  "gap-1": "gap: 0.25rem;",
  "gap-1.5": "gap: 0.375rem;",
  "gap-2": "gap: 0.5rem;",
  "gap-2.5": "gap: 0.625rem;",
  "gap-3": "gap: 0.75rem;",
  "gap-3.5": "gap: 0.875rem;",
  "gap-5": "gap: 1.25rem;",
  "gap-7": "gap: 1.75rem;",
  "gap-9": "gap: 2.25rem;",
  "gap-10": "gap: 2.5rem;",
  "gap-11": "gap: 2.75rem;",
  "gap-14": "gap: 3.5rem;",
  "gap-28": "gap: 7rem;",
  "gap-36": "gap: 9rem;",
  "gap-44": "gap: 11rem;",
  "space-x-0": "column-gap: 0;",
  "space-x-1": "column-gap: 0.25rem;",
  "space-x-2": "column-gap: 0.5rem;",
  "space-x-3": "column-gap: 0.75rem;",
  "space-x-4": "column-gap: 1rem;",
  "space-x-5": "column-gap: 1.25rem;",
  "space-x-6": "column-gap: 1.5rem;",
  "space-x-8": "column-gap: 2rem;",
  "space-x-10": "column-gap: 2.5rem;",
  "space-x-12": "column-gap: 3rem;",
  "space-x-16": "column-gap: 4rem;",
  "space-x-20": "column-gap: 5rem;",
  "space-x-24": "column-gap: 6rem;",
  "space-x-32": "column-gap: 8rem;",
  "space-x-40": "column-gap: 10rem;",
  "space-x-48": "column-gap: 12rem;",
  "space-x-56": "column-gap: 14rem;",
  "space-x-64": "column-gap: 16rem;",
  "space-x-72": "column-gap: 18rem;",
  "space-x-80": "column-gap: 20rem;",
  "space-x-96": "column-gap: 24rem;",
  "space-x-px": "column-gap: 1px;",
  "space-y-0": "row-gap: 0;",
  "space-y-1": "row-gap: 0.25rem;",
  "space-y-2": "row-gap: 0.5rem;",
  "space-y-3": "row-gap: 0.75rem;",
  "space-y-4": "row-gap: 1rem;",
  "space-y-5": "row-gap: 1.25rem;",
  "space-y-6": "row-gap: 1.5rem;",
  "space-y-8": "row-gap: 2rem;",
  "space-y-10": "row-gap: 2.5rem;",
  "space-y-12": "row-gap: 3rem;",
  "space-y-16": "row-gap: 4rem;",
  "space-y-20": "row-gap: 5rem;",
  "space-y-24": "row-gap: 6rem;",
  "space-y-32": "row-gap: 8rem;",
  "space-y-40": "row-gap: 10rem;",
  "space-y-48": "row-gap: 12rem;",
  "space-y-56": "row-gap: 14rem;",
  "space-y-64": "row-gap: 16rem;",
  "space-y-72": "row-gap: 18rem;",
  "space-y-80": "row-gap: 20rem;",
  "space-y-96": "row-gap: 24rem;",
  "space-y-px": "row-gap: 1px;",
  "place-items-center": "place-items: center;",
  "place-content-center": "place-content: center;",
  "place-content-start": "place-content: start;",
  "place-content-end": "place-content: end;",
  "place-content-between": "place-content: space-between;",
  "place-content-around": "place-content: space-around;",
  "place-content-evenly": "place-content: space-evenly;",
  "place-content-stretch": "place-content: stretch;",
  "place-self-center": "place-self: center;",
  "place-self-start": "place-self: start;",
  "place-self-end": "place-self: end;",
  "place-self-auto": "place-self: auto;",
  "place-self-stretch": "place-self: stretch;",
  "grid-flow-row": "grid-auto-flow: row;",
  "grid-flow-col": "grid-auto-flow: column;",
  "grid-flow-row-dense": "grid-auto-flow: row dense;",
  "grid-flow-col-dense": "grid-auto-flow: column dense;",
  "col-auto": "grid-column: auto;",
  "col-span-full": "grid-column: 1 / -1;",
  "row-auto": "grid-row: auto;",
  "row-span-full": "grid-row: 1 / -1;",
  "grid-cols-none": "grid-template-columns: none;",
  "grid-rows-none": "grid-template-rows: none;",
  "grid-cols-1fr": "grid-template-columns: 1fr;",
  "grid-cols-2fr": "grid-template-columns: 2fr;",
  "grid-cols-3fr": "grid-template-columns: 3fr;",
  "grid-cols-4fr": "grid-template-columns: 4fr;",
  "grid-cols-5fr": "grid-template-columns: 5fr;",
  "grid-cols-6fr": "grid-template-columns: 6fr;",
  "grid-cols-7fr": "grid-template-columns: 7fr;",
  "grid-cols-8fr": "grid-template-columns: 8fr;",
  "grid-cols-9fr": "grid-template-columns: 9fr;",
  "grid-cols-10fr": "grid-template-columns: 10fr;",
  "grid-cols-11fr": "grid-template-columns: 11fr;",
  "grid-cols-12fr": "grid-template-columns: 12fr;",
  "grid-rows-1fr": "grid-template-rows: 1fr;",
  "grid-rows-2fr": "grid-template-rows: 2fr;",
  "grid-rows-3fr": "grid-template-rows: 3fr;",
  "grid-rows-4fr": "grid-template-rows: 4fr;",
  "grid-rows-5fr": "grid-template-rows: 5fr;",
  "grid-rows-6fr": "grid-template-rows: 6fr;",
  "grid-rows-7fr": "grid-template-rows: 7fr;",
  "grid-rows-8fr": "grid-template-rows: 8fr;",
  "grid-rows-9fr": "grid-template-rows: 9fr;",
  "grid-rows-10fr": "grid-template-rows: 10fr;",
  "grid-rows-11fr": "grid-template-rows: 11fr;",
  "grid-rows-12fr": "grid-template-rows: 12fr;",
  "grid-cols-min": "grid-template-columns: min-content;",
  "grid-cols-max": "grid-template-columns: max-content;",
  "grid-cols-auto": "grid-template-columns: auto;",
  "grid-rows-min": "grid-template-rows: min-content;",
  "grid-rows-max": "grid-template-rows: max-content;",
  "grid-rows-auto": "grid-template-rows: auto;",
  "col-span-auto": "grid-column: span auto;",
  "col-start-auto": "grid-column-start: auto;",
  "col-end-auto": "grid-column-end: auto;",
  "row-span-auto": "grid-row: span auto;",
  "row-start-auto": "grid-row-start: auto;",
  "row-end-auto": "grid-row-end: auto;",
} as const;
