export const typographyMapping: Record<string, string> = {
  // Typography
  "text-left": "text-align: left;",
  "text-center": "text-align: center;",
  "text-right": "text-align: right;",
  "font-thin": "font-weight: 100;",
  "font-light": "font-weight: 300;",
  "font-normal": "font-weight: 400;",
  "font-medium": "font-weight: 500;",
  "font-bold": "font-weight: 700;",
  "font-black": "font-weight: 900;",
  "not-italic": "font-style: normal;",
  italic: "font-style: italic;",
  underline: "text-decoration: underline;",
  "line-through": "text-decoration: line-through;",
  "no-underline": "text-decoration: none;",
  uppercase: "text-transform: uppercase;",
  lowercase: "text-transform: lowercase;",
  capitalize: "text-transform: capitalize;",
  "normal-case": "text-transform: none;",
  truncate: "overflow: hidden; text-overflow: ellipsis; white-space: nowrap;",
  "break-words": "word-wrap: break-word;",
  "tracking-tighter": "letter-spacing: -0.05em;",
  "tracking-tight": "letter-spacing: -0.025em;",
  "tracking-normal": "letter-spacing: 0;",
  "tracking-wide": "letter-spacing: 0.025em;",
  "tracking-wider": "letter-spacing: 0.05em;",
  "tracking-widest": "letter-spacing: 0.1em;",
  "leading-3": "line-height: 0.75rem;",
  "leading-4": "line-height: 1rem;",
  "leading-5": "line-height: 1.25rem;",
  "leading-6": "line-height: 1.5rem;",
  "leading-7": "line-height: 1.75rem;",
  "leading-8": "line-height: 2rem;",
  "leading-9": "line-height: 2.25rem;",
  "leading-10": "line-height: 2.5rem;",
  "text-xs": "font-size: 0.75rem;",
  "text-sm": "font-size: 0.875rem;",
  "text-base": "font-size: 1rem;",
  "text-lg": "font-size: 1.125rem;",
  "text-xl": "font-size: 1.25rem;",
  "text-2xl": "font-size: 1.5rem;",
  "text-3xl": "font-size: 1.875rem;",
  "text-4xl": "font-size: 2.25rem;",
  "text-5xl": "font-size: 3rem;",
  "text-6xl": "font-size: 4rem;",
  "text-7xl": "font-size: 5rem;",
  "text-8xl": "font-size: 6rem;",
  "text-9xl": "font-size: 7rem;",
  "text-10xl": "font-size: 8rem;",
  "font-sans": "font-family: system-ui, sans-serif;",
  "font-serif": "font-family: Georgia, Cambria, Times New Roman, Times, serif;",
  "font-mono": "font-family: Menlo, Monaco, Consolas, Liberation Mono, Courier New, monospace;",
  "font-[family-name:var(--font-geist-sans)]": "font-family: var(--font-geist-sans);",
  
  "bg-opacity-0": "opacity: 0;",
  "bg-opacity-25": "opacity: 0.25;",
  "bg-opacity-50": "opacity: 0.5;",
  "bg-opacity-75": "opacity: 0.75;",
  "bg-opacity-100": "opacity: 1;",
} as const;
